<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <StaticLinkNetCord Condition="'$(PublishProfile)' == 'LinuxStatic'">true</StaticLinkNetCord>
        <StripSymbols>true</StripSymbols>
        <DebugType>portable</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="libsodium" Version="1.0.22" Condition="'$(StaticLinkNetCord)' != 'true'" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
        <PackageReference Include="NetCord" Version="1.0.0-beta.21" />
        <PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.21" />
        <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.21" />
        <PackageReference Include="NetCord.Services" Version="1.0.0-beta.21" />

        <None Update="appsettings.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>

    </ItemGroup>

    <ItemGroup>
      <Folder Include="tracks\" />
    </ItemGroup>

    <Import Project="Native/StaticLink.targets" />
    <Import Project="Native/MacOS.targets" />
</Project>
